# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-07 12:04
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hex',
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=colorfield.fields.ColorField(default='#3498db', max_length=10),
        ),
    ]
