# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ue', '0003_event_yolo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='yolo',
        ),
    ]
